### ISSUE TITLE
no experiment directory is created

### ISSUE THREAD

**Issue by Rigel-Alves** [score-p/scorep_binding_python#113]
Hi,

I need to profile/trace simulation codes written in Python which are run in parallel. The following works normally:

`srun -n 1 -o %j-%t.cout -e %j-%t.cerr -p haswell --mem-per-cpu 2583 python -m scorep test_sleep.py`

But if I try adding the MPI flag:

`srun -n 1 -o %j-%t.cout -e %j-%t.cerr -p haswell --mem-per-cpu 2583 python -m scorep --mpp=mpi test_sleep.py`

No experiment directory (`scorep-...`) is created. Without the `--mpp=mpi` flag, I am unable to run the Score-P module in parallel (what would be the next step). Could you help me figure out what is going on?

Thanks a lot,

**Comment by AndreasGocht** [comment]
Hey,

Is there any MPI communication done in test_sleep.py? There needs to be at least an `MPI_Init()`. If you use `mpi4py`, this is done during the module import as far as I remember.

Best,

Andreas

**Comment by Rigel-Alves** [comment]
Thanks Andreas for the prompt reply. I was trying to go step by step towards my final goal. I didn't understand why the experiment directory would not be created when adding the `--mpp=mpi` flag (there is no error or warning message). It is not created either when doing:

`srun -n 2 -o %j-%t.cout -e %j-%t.cerr -p haswell --mem-per-cpu 2583 python -m scorep --mpp=mpi test_sleep.py`

Probably because there is no MPI communication in `test_sleep.py` (as you said), but I think the experiment directory should be created anyway (with the same contents as when `--mpp=mpi` is not used). I tried running a DLR Python code which does have communication and the Score-P experiment directory is created, as expected; but with a warning message:

`[Score-P] src/adapters/mpi/SCOREP_Mpi_Env.c:230: Warning: MPI environment initialization request and provided level exceed MPI_THREAD_FUNNELED!`

**Comment by rtschueter** [comment]
In our experiments this warning could be ignored while instrumenting FSDM with Score-P.

Cheers
Ronny

Am 29.10.2020 um 12:14 schrieb Rigel-Alves <notifications@github.com>:

﻿

Thanks Andreas for the prompt reply. I was trying to go step by step towards my final goal. I didn't understand why the experiment directory would not be created when adding the --mpp=mpi flag (there is no error or warning message). It is not created either when doing:

srun -n 2 -o %j-%t.cout -e %j-%t.cerr -p haswell --mem-per-cpu 2583 python -m scorep --mpp=mpi test_sleep.py

Probably because there is no MPI communication in test_sleep.py (as you said), but I think the experiment directory should be created anyway (with the same contents as when --mpp=mpi is not used). I tried running a DLR Python code which does have communication and the Score-P experiment directory is created, as expected; but with a warning message:

[Score-P] src/adapters/mpi/SCOREP_Mpi_Env.c:230: Warning: MPI environment initialization request and provided level exceed MPI_THREAD_FUNNELED!

**Comment by AndreasGocht** [comment]
Hi,

> Probably because there is no MPI communication in test_sleep.py (as you said), but I think the experiment directory should be created anyway (with the same contents as when --mpp=mpi is not used). I tried running a DLR Python code which does have communication and the Score-P experiment directory is created, as expected; but with a warning message:

As I understand Score-P an MPI, that is not possible: if you start two processes, and imeadetly create an experiment directory, both would try to create the same directory, which would obviously lead to a conflict. To avoid that Score-P has to figure out which process is supposed to create the directory. To do so, communication is needed, which only can be done after MPI_Init() is called.

So if you tell Score-P that you are using MPI (e.g. with `--mpp=mpi`) Score-P waits for an `MPI_Init()` (e.g. from mpi4py).

Having that said, I wonder if python multiprocessing code can be traced by simply adding mpi4py at the right places. 

Anyway, about
```
[Score-P] src/adapters/mpi/SCOREP_Mpi_Env.c:230: Warning: MPI environment initialization request and provided level exceed MPI_THREAD_FUNNELED!
```
Please have a look at https://bitbucket.org/mpi4py/mpi4py/issues/80/mpi_thread_multiple-vs-mpi_thread_single . There is a way to disable threads for mpi4py.

Best,

Andreas

**Comment by Rigel-Alves** [comment]
Thanks Andreas once again. In this case, it might be good to issue a warning message to the user; something like:

`Warning: Score-P Python module has been requested to use MPI, but MPI_Init() has not been called by the code. No experiment directory is created in such cases.`

Just to avoid other people running into the same thing and not knowing what is going on.

**Comment by AndreasGocht** [comment]
Dear Rigel,

this might be a feature for Score-P itself. If you would like to have this feature, please ask the Score-P Support Mailing list.

Best,

Andreas
