### ISSUE TITLE
Installing Score-P for Python+MPI

### ISSUE THREAD

**Issue by abidmalikwaterloo** [score-p/scorep_binding_python#22]
I am trying to install score-p for python+MPI. I am a bit confused about the direction. What does 

---
You need to have scorep-config in your PATH variable.

----
means?

**Comment by abidmalikwaterloo** [comment]
I don't see any installation direction ( libraries/source files) for score-p here that I need to install using makefile

**Comment by AndreasGocht** [comment]
Hey,

in order to use the Score-P bindings you need to install Score-P first. You'll get it from https://www.vi-hps.org/projects/score-p/ .
For the beginning I recommend you to install OpenMPI
```
apt install openmpi-common
```
Next you need to configure, build and install Score-P
```
mkdir build
cd build
../configure --with-mpi=openmpi \
             --enable-shared \
             --prefix=/usr/local/
make
make install
```

Finally you need to be sure, that `/usr/local/bin` is in your path, e.g. by doing:
```
export PATH=$PATH:/usr/local/bin
```

Now you can install the Score-P Python bindings doing

```
git clone https://github.com/score-p/scorep_binding_python.git
cd scorep_binding_python
pip install .
```

I hope this short how to helps.

Best,

Andreas

**Comment by abidmalikwaterloo** [comment]
@AndreasGocht  Thanks. I am getting the following when I used pip install in scorep_binding_python directory ( after installing Score-P successfully )
```
pip install
ERROR: You must give at least one requirement to install (see "pip help install")

```

I think it is expecting an argument with the install, pip install <something>

**Comment by AndreasGocht** [comment]
Yes :smile: you forgot the `.` after the `install`.
Best
Andreas

**Comment by abidmalikwaterloo** [comment]
@AndreasGocht  Yes ..  : ) I figured it out later and was able to build it. thanks
